DateTime? _dt(dynamic v) => v == null ? null : DateTime.tryParse(v.toString());
String? _date(DateTime? v) => v?.toIso8601String().split('T').first;

class ApiEnvelope<T> { final bool success; final String message; final T data; ApiEnvelope(this.success,this.message,this.data); }

class AuthResult { final int userId; final String accessToken; final String message; AuthResult({required this.userId,required this.accessToken,required this.message}); factory AuthResult.fromJson(Map<String,dynamic> j)=>AuthResult(userId:(j['userId'] as num).toInt(),accessToken:j['accessToken']??'',message:j['message']??''); }

class UserProfile { int? id,userId,yearsOfExperience; String? firstName,lastName,email,phone,headline,bio,currentJobTitle,city,state,country,linkedinUrl,githubUrl,portfolioUrl,profilePhotoUrl; DateTime? dateOfBirth,createdAt,updatedAt; String? gender;
  UserProfile.fromJson(Map<String,dynamic> j){id=(j['id'] as num?)?.toInt();userId=(j['userId'] as num?)?.toInt();yearsOfExperience=(j['yearsOfExperience'] as num?)?.toInt();firstName=j['firstName'];lastName=j['lastName'];email=j['email'];phone=j['phone'];headline=j['headline'];bio=j['bio'];currentJobTitle=j['currentJobTitle'];city=j['city'];state=j['state'];country=j['country'];linkedinUrl=j['linkedinUrl'];githubUrl=j['githubUrl'];portfolioUrl=j['portfolioUrl'];profilePhotoUrl=j['profilePhotoUrl'];gender=j['gender'];dateOfBirth=_dt(j['dateOfBirth']);createdAt=_dt(j['createdAt']);updatedAt=_dt(j['updatedAt']);}
}

class Education {int? id; String? institutionName,degree,fieldOfStudy,grade,description; DateTime? startDate,endDate; bool? currentlyStudying; Education.fromJson(Map<String,dynamic>j){id=(j['id']as num?)?.toInt();institutionName=j['institutionName'];degree=j['degree'];fieldOfStudy=j['fieldOfStudy'];grade=j['grade'];description=j['description'];startDate=_dt(j['startDate']);endDate=_dt(j['endDate']);currentlyStudying=j['currentlyStudying'];}}
class Experience {int? id; String? companyName,jobTitle,employmentType,location,description; DateTime? startDate,endDate,createdAt,updatedAt; bool? currentlyWorking; Experience.fromJson(Map<String,dynamic>j){id=(j['id']as num?)?.toInt();companyName=j['companyName'];jobTitle=j['jobTitle'];employmentType=j['employmentType'];location=j['location'];description=j['description'];startDate=_dt(j['startDate']);endDate=_dt(j['endDate']);currentlyWorking=j['currentlyWorking'];createdAt=_dt(j['createdAt']);updatedAt=_dt(j['updatedAt']);}}
class Skill {int? id; String? skillName,proficiency; Skill.fromJson(Map<String,dynamic>j){id=(j['id']as num?)?.toInt();skillName=j['skillName'];proficiency=j['proficiency'];}}
class Project {int? id; String? projectName,description,technologies,githubUrl,liveUrl; bool? currentlyWorking; DateTime? startDate,endDate; Project.fromJson(Map<String,dynamic>j){id=(j['id']as num?)?.toInt();projectName=j['projectName'];description=j['description'];technologies=j['technologies'];githubUrl=j['githubUrl'];liveUrl=j['liveUrl'];currentlyWorking=j['currentlyWorking'];startDate=_dt(j['startDate']);endDate=_dt(j['endDate']);}}
class Certification {int? id; String? certificationName,issuingOrganization,credentialId,credentialUrl; DateTime? issueDate,expiryDate; Certification.fromJson(Map<String,dynamic>j){id=(j['id']as num?)?.toInt();certificationName=j['certificationName'];issuingOrganization=j['issuingOrganization'];credentialId=j['credentialId'];credentialUrl=j['credentialUrl'];issueDate=_dt(j['issueDate']);expiryDate=_dt(j['expiryDate']);}}
class Language {int? id; String? languageName,proficiency; Language.fromJson(Map<String,dynamic>j){id=(j['id']as num?)?.toInt();languageName=j['languageName'];proficiency=j['proficiency'];}}
class SocialLinks {int? id; String? githubUrl,linkedinUrl,portfolioUrl,leetcodeUrl,hackerrankUrl,codeforcesUrl,codechefUrl,twitterUrl,personalWebsite; SocialLinks.fromJson(Map<String,dynamic>j){id=(j['id']as num?)?.toInt();githubUrl=j['githubUrl'];linkedinUrl=j['linkedinUrl'];portfolioUrl=j['portfolioUrl'];leetcodeUrl=j['leetcodeUrl'];hackerrankUrl=j['hackerrankUrl'];codeforcesUrl=j['codeforcesUrl'];codechefUrl=j['codechefUrl'];twitterUrl=j['twitterUrl'];personalWebsite=j['personalWebsite'];}}
class Resume {int? id; String? title,professionalSummary,templateType; bool? isPublic; DateTime? createdAt,updatedAt; Resume.fromJson(Map<String,dynamic>j){id=(j['id']as num?)?.toInt();title=j['title'];professionalSummary=j['professionalSummary'];templateType=j['templateType'];isPublic=j['isPublic'];createdAt=_dt(j['createdAt']);updatedAt=_dt(j['updatedAt']);}}
class AtsAnalysis {int? id,resumeId,atsScore,keywordScore,skillsScore,experienceScore,educationScore,formattingScore; String? analysisType,jobTitle,jobDescription; List<String> matchedKeywords=[],missingKeywords=[],strengths=[],weaknesses=[],suggestions=[]; DateTime? createdAt,updatedAt; AtsAnalysis.fromJson(Map<String,dynamic>j){id=(j['id']as num?)?.toInt();resumeId=(j['resumeId']as num?)?.toInt();atsScore=(j['atsScore']as num?)?.toInt();keywordScore=(j['keywordScore']as num?)?.toInt();skillsScore=(j['skillsScore']as num?)?.toInt();experienceScore=(j['experienceScore']as num?)?.toInt();educationScore=(j['educationScore']as num?)?.toInt();formattingScore=(j['formattingScore']as num?)?.toInt();analysisType=j['analysisType'];jobTitle=j['jobTitle'];jobDescription=j['jobDescription'];matchedKeywords=List<String>.from(j['matchedKeywords']??[]);missingKeywords=List<String>.from(j['missingKeywords']??[]);strengths=List<String>.from(j['strengths']??[]);weaknesses=List<String>.from(j['weaknesses']??[]);suggestions=List<String>.from(j['suggestions']??[]);createdAt=_dt(j['createdAt']);updatedAt=_dt(j['updatedAt']);}}
class SalaryEstimate {int? id,experienceYears; String? jobTitle,location,industry,currency,marketPosition,createdAt; double? minimumSalary,expectedSalary,maximumSalary; List<String> factors=[],skillNames=[]; SalaryEstimate.fromJson(Map<String,dynamic>j){id=(j['id']as num?)?.toInt();experienceYears=(j['experienceYears']as num?)?.toInt();jobTitle=j['jobTitle'];location=j['location'];industry=j['industry'];currency=j['currency'];marketPosition=j['marketPosition'];createdAt=j['createdAt']?.toString();minimumSalary=(j['minimumSalary']as num?)?.toDouble();expectedSalary=(j['expectedSalary']as num?)?.toDouble();maximumSalary=(j['maximumSalary']as num?)?.toDouble();factors=List<String>.from(j['factors']??[]);skillNames=List<String>.from(j['skillNames']??[]);}}
class SalaryCompare {double? currentSalary,expectedSalary,minimumSalary,maximumSalary,differenceFromExpected,percentageDifference; String? marketPosition,message; SalaryEstimate? estimate; SalaryCompare.fromJson(Map<String,dynamic>j){currentSalary=(j['currentSalary']as num?)?.toDouble();expectedSalary=(j['expectedSalary']as num?)?.toDouble();minimumSalary=(j['minimumSalary']as num?)?.toDouble();maximumSalary=(j['maximumSalary']as num?)?.toDouble();differenceFromExpected=(j['differenceFromExpected']as num?)?.toDouble();percentageDifference=(j['percentageDifference']as num?)?.toDouble();marketPosition=j['marketPosition'];message=j['message'];estimate=j['estimate']==null?null:SalaryEstimate.fromJson(j['estimate']);}}
class CareerCoach {String? source,careerAssessment; List<String> recommendedRoles=[],skillGaps=[],prioritySkills=[],nextActions=[]; List<RoadmapPhase> roadmap=[]; CareerCoach.fromJson(Map<String,dynamic>j){source=j['source'];careerAssessment=j['careerAssessment'];recommendedRoles=List<String>.from(j['recommendedRoles']??[]);skillGaps=List<String>.from(j['skillGaps']??[]);prioritySkills=List<String>.from(j['prioritySkills']??[]);nextActions=List<String>.from(j['nextActions']??[]);roadmap=(j['roadmap']??[]).map<RoadmapPhase>((e)=>RoadmapPhase.fromJson(e)).toList();}}
class RoadmapPhase {int? phase;String? title,duration;List<String>skills=[];RoadmapPhase.fromJson(Map<String,dynamic>j){phase=(j['phase']as num?)?.toInt();title=j['title'];duration=j['duration'];skills=List<String>.from(j['skills']??[]);}}
String? dateOnly(DateTime? d)=>_date(d);
